# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass=prologepilog --verify-machineinstrs %s -o - | FileCheck %s

# Isolated test for the prologepilog (eliminateFrameIndex) expansion of the
# composite ePSRFLdF spill/reload pseudos. The input is already post-RA (the
# VST_PLFR_SPILL / VLDA_PLFR_SPILL pseudos reference physical registers and a
# stack slot); this verifies just the lowering into native store/load
# instructions, including the per-sub-register stack offsets and the FIFO
# bounce copy that VLDA_PLFR_SPILL materializes for the reload.

---
name:            test_epsrfldf_prologepilog
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
frameInfo:
  maxAlignment:    64
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 136, alignment: 64 }
body:             |
  bb.0.entry:
    liveins: $plfr0
    ; CHECK-LABEL: name: test_epsrfldf_prologepilog
    ; CHECK: liveins: $plfr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 192, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_scalar_spill killed $lr, -56, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: renamable $y0 = COPY $lf0
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -192, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x1, -128, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_spill $r24, -64, implicit $sp :: (store (s32) into %stack.0 + 128, align 64)
    ; CHECK-NEXT: ST_dms_sts_scalar_spill $p0, -60, implicit $sp :: (store (s32) into %stack.0 + 132, basealign 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2ps, implicit-def $lr
    ; CHECK-NEXT: $x0 = VLDA_dmx_lda_x_spill -192, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $x1 = VLDA_dmx_lda_x_spill -128, implicit $sp :: (load (s512) from %stack.0 + 64)
    ; CHECK-NEXT: $r24 = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0 + 128, align 64)
    ; CHECK-NEXT: $p0 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.0 + 132, basealign 64)
    ; CHECK-NEXT: $lf0 = COPY killed $y0
    ; CHECK-NEXT: $lr = LDA_dms_lda_scalar_spill -56, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -192, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $plfr0
    renamable $y0 = COPY $lf0
    VST_PLFR_SPILL killed renamable $y0, $r24, $p0, %stack.0, implicit $sp :: (store (s1088) into %stack.0, align 64)
    PseudoJL 32, csr_aie2ps, implicit-def $lr
    dead renamable $y0, renamable $plfr0 = VLDA_PLFR_SPILL %stack.0, implicit $sp :: (load (s1088) from %stack.0, align 64)
    PseudoRET implicit $lr, implicit killed renamable $plfr0
...
