# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# Outer-loop pipeliner epilog shape -- full DM-family vlda chain.
#
# Inner loop (bb.1) writes %acc:acc2048 via vmac; after RA it lands on a
# physical $dm* family. The tagged outer-loop epilog (bb.2) stores that
# accumulator (vst.srs.4x) and then refills the four BM sub-registers of
# the same DM family via a chained post-increment vlda sequence. Shape
# extracted from gemm_int8_psum after AIEOuterLoopPipeliner.
#
# AIEOuterLoopEpilogRename splits the chain-head vreg onto a different
# DM family and inserts one acc2048 COPY before the back-edge to restore
# the original family, breaking the WAR edge that otherwise constrains
# how early the chain head can be scheduled.

# RUN: llc -mtriple=aie2ps -verify-machineinstrs --aie-reg-rewrite-mode=basic \
# RUN:   --start-before=greedy --stop-after=virtregrewriter \
# RUN:   %s -o - | FileCheck %s

--- |
  target triple = "aie2ps"

  define void @dm_family_epilog(ptr addrspace(5) %p_in, ptr %p_chain, ptr addrspace(6) %p_out) {
  entry:
    br label %inner.loop

  inner.loop:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %inner.loop, label %outer.epilog

  outer.epilog:
    br label %exit, !llvm.loop !0

  exit:
    ret void
  }

  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1, !2}
  !1 = !{!"llvm.loop.hint.aie_outerloop_pipeliner_success", i64 1}
  !2 = !{!"llvm.loop.hint.aie-outer-loop-epilog", i64 1}
...
---
name:            dm_family_epilog
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: dm_family_epilog
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $r0, $r8, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm0 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.inner.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $p1, $p2, $r0, $r8, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm0 = VMAC_vmac_vmul_cm_core_X_X killed renamable $dm0, renamable $x0, renamable $x0, renamable $r8
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoJNZ renamable $r0, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.outer.epilog:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $p1, $p2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $srssign0 = MOVX_mvx_cr_imm 0
  ; CHECK-NEXT:   dead renamable $p1 = VST_SRS_4x_dmx_sts_srs_dm_pstm_nrm_imm_srsSign0 killed renamable $dm0, undef renamable $s0, killed renamable $p1, 64, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
  ; CHECK-NEXT:   renamable $bmll1, renamable $p2 = VLDA_dmx_lda_bm_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $bmlh1, renamable $p2 = VLDA_dmx_lda_bm_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $bmhl1, renamable $p2 = VLDA_dmx_lda_bm_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $bmhh1, dead renamable $p2 = VLDA_dmx_lda_bm_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   dead renamable $dm0 = COPY killed renamable $dm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.exit:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1
    liveins: $p0, $p1, $p2, $r0, $r8, $x0

    %0:ep_as_32bit = COPY $p0
    %1:ep_as_32bit = COPY $p1
    %2:ep_as_32bit = COPY $p2
    %3:mlockid_reg = COPY $r0
    %4:vec512 = COPY $x0
    %5:mrv8 = COPY $r8
    %6:acc2048 = IMPLICIT_DEF

  bb.1.inner.loop:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    %6:acc2048 = VMAC_vmac_vmul_cm_core_X_X %6, %4, %4, %5
    %3:mlockid_reg = nsw ADD_add_r_ri %3, -1, implicit-def dead $srcarry
    PseudoJNZ %3, %bb.1
    PseudoJ_jump_imm %bb.2

  bb.2.outer.epilog:
    successors: %bb.3

    $srssign0 = MOVX_mvx_cr_imm 0
    %1:ep_as_32bit = VST_SRS_4x_dmx_sts_srs_dm_pstm_nrm_imm_srsSign0 %6, undef %20:es, %1, 64, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0

    undef %30.sub_512_acc_lo:acc2048, %2:ep_as_32bit = VLDA_dmx_lda_bm_ld_pstm_nrm_imm %2, 64
    %30.sub_512_acc_hi:acc2048, %2:ep_as_32bit = VLDA_dmx_lda_bm_ld_pstm_nrm_imm %2, 64
    %30.sub_1024_acc_hi_then_sub_512_acc_lo:acc2048, %2:ep_as_32bit = VLDA_dmx_lda_bm_ld_pstm_nrm_imm %2, 64
    %30.sub_1024_acc_hi_then_sub_512_acc_hi:acc2048, %2:ep_as_32bit = VLDA_dmx_lda_bm_ld_pstm_nrm_imm %2, 64

  bb.3.exit:
    PseudoRET implicit $lr
...
