# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# Outer-loop pipeliner epilog shape -- X-register (512-bit) vlda chain.
#
# Different register file than the BM/DM case: the inner loop produces
# an X-bank result, the epilog stores it, then refills the same X
# register via a chained vlda sequence using
# VLDA_dmx_lda_x_ld_pstm_nrm_imm.
#
# AIEOuterLoopEpilogRename renames the WAR-blocked vlda onto a free X
# register and inserts one 512-bit X COPY before the back-edge to restore
# the original register, breaking the post-pipeliner WAR.

# RUN: llc -mtriple=aie2ps -verify-machineinstrs --aie-reg-rewrite-mode=basic \
# RUN:   --start-before=greedy --stop-after=virtregrewriter \
# RUN:   %s -o - | FileCheck %s

--- |
  target triple = "aie2ps"

  define void @x_reg_epilog(ptr addrspace(5) %p_in, ptr %p_chain, ptr addrspace(6) %p_out) {
  entry:
    br label %inner.loop

  inner.loop:
    %dec = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %dec, label %inner.loop, label %outer.epilog

  outer.epilog:
    br label %exit, !llvm.loop !0

  exit:
    ret void
  }

  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1, !2}
  !1 = !{!"llvm.loop.hint.aie_outerloop_pipeliner_success", i64 1}
  !2 = !{!"llvm.loop.hint.aie-outer-loop-epilog", i64 1}
...
---
name:            x_reg_epilog
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: x_reg_epilog
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $r0, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.inner.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $p1, $p2, $r0, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x2 = VADD_16 killed renamable $x2, renamable $x0, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   renamable $r0 = nsw ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoJNZ renamable $r0, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.outer.epilog:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $p1, $p2, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x2, killed renamable $p1, 64
  ; CHECK-NEXT:   renamable $x0, renamable $p2 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $x8, renamable $p2 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $x4, renamable $p2 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $x6, dead renamable $p2 = VLDA_dmx_lda_x_ld_pstm_nrm_imm killed renamable $p2, 64
  ; CHECK-NEXT:   renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x0, killed renamable $p1, 64
  ; CHECK-NEXT:   renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm renamable $x8, killed renamable $p1, 64
  ; CHECK-NEXT:   renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x4, killed renamable $p1, 64
  ; CHECK-NEXT:   dead renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x6, killed renamable $p1, 64
  ; CHECK-NEXT:   dead renamable $x2 = COPY killed renamable $x8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.exit:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1
    liveins: $p0, $p1, $p2, $r0, $x0, $x2

    %0:ep_as_32bit = COPY $p0
    %1:ep_as_32bit = COPY $p1
    %2:ep_as_32bit = COPY $p2
    %3:mlockid_reg = COPY $r0
    %4:vec512 = COPY $x0
    %5:vec512 = COPY $x2

  bb.1.inner.loop:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    %5:vec512 = VADD_16 %5, %4, implicit $crbf8conf, implicit $crfp8conf
    %3:mlockid_reg = nsw ADD_add_r_ri %3, -1, implicit-def dead $srcarry
    PseudoJNZ %3, %bb.1
    PseudoJ_jump_imm %bb.2

  bb.2.outer.epilog:
    successors: %bb.3

    %1:ep_as_32bit = VST_dmx_sts_x_st_pstm_nrm_imm %5, %1, 64

    %10:vec512, %2:ep_as_32bit = VLDA_dmx_lda_x_ld_pstm_nrm_imm %2, 64
    %11:vec512, %2:ep_as_32bit = VLDA_dmx_lda_x_ld_pstm_nrm_imm %2, 64
    %12:vec512, %2:ep_as_32bit = VLDA_dmx_lda_x_ld_pstm_nrm_imm %2, 64
    %13:vec512, %2:ep_as_32bit = VLDA_dmx_lda_x_ld_pstm_nrm_imm %2, 64
    %1:ep_as_32bit = VST_dmx_sts_x_st_pstm_nrm_imm %10, %1, 64
    %1:ep_as_32bit = VST_dmx_sts_x_st_pstm_nrm_imm %11, %1, 64
    %1:ep_as_32bit = VST_dmx_sts_x_st_pstm_nrm_imm %12, %1, 64
    %1:ep_as_32bit = VST_dmx_sts_x_st_pstm_nrm_imm %13, %1, 64

  bb.3.exit:
    PseudoRET implicit $lr
...
