# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-cluster-base-address %s -verify-machineinstrs -o - | FileCheck %s

# Test that bare load/store instructions using a PHI-defined pointer (offset 0)
# get a G_PTR_ADD +0 inserted when the PHI also has G_PTR_ADD users whose
# outputs feed load/store instructions, enabling post-increment chaining.

# Positive test: PHI with 3 PTR_ADD users feeding loads (-128, +128, +512),
# plus a bare load at offset 0. The bare load gets PTR_ADD +0 and all loads
# end up chained.
---
name:            phi_load_bare_offset_zero
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi_load_bare_offset_zero
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI %5(p0), %bb.1, [[PTR_ADD]](p0), %bb.0
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI %7(s32), %bb.1, [[COPY1]](s32), %bb.0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -128
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PHI]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD2]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C5]](s20)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD3]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 512
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 384
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C7]](s20)
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI1]], [[C8]]
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[ADD]](s32), [[C9]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[LOAD1]](<16 x s32>)
  ; CHECK-NEXT:   $x4 = COPY [[LOAD2]](<16 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x2, implicit $x4
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %100:_(s20) = G_CONSTANT i20 256
    %2:_(p0) = G_PTR_ADD %0, %100(s20)
    G_BR %bb.1

  bb.1:
    successors: %bb.2, %bb.1
    %3:_(p0) = G_PHI %10(p0), %bb.1, %2(p0), %bb.0
    %13:_(s32) = G_PHI %15(s32), %bb.1, %1(s32), %bb.0
    %4:_(s20) = G_CONSTANT i20 -128
    %5:_(p0) = G_PTR_ADD %3, %4(s20)
    %6:_(<16 x s32>) = G_LOAD %5(p0) :: (load (<16 x s32>), align 64)
    %7:_(<16 x s32>) = G_LOAD %3(p0) :: (load (<16 x s32>), align 64)
    %8:_(s20) = G_CONSTANT i20 128
    %9:_(p0) = G_PTR_ADD %3, %8(s20)
    %11:_(<16 x s32>) = G_LOAD %9(p0) :: (load (<16 x s32>), align 64)
    %12:_(s20) = G_CONSTANT i20 512
    %10:_(p0) = G_PTR_ADD %3, %12(s20)
    %14:_(s32) = G_CONSTANT i32 -1
    %15:_(s32) = G_ADD %13, %14
    %16:_(s32) = G_CONSTANT i32 0
    %17:_(s1) = G_ICMP intpred(eq), %15(s32), %16
    G_BRCOND %17(s1), %bb.2
    G_BR %bb.1

  bb.2:
    $x0 = COPY %6
    $x2 = COPY %7
    $x4 = COPY %11
    PseudoRET implicit $lr, implicit $x0, implicit $x2, implicit $x4
...

# Negative test: PHI has only 1 PTR_ADD feeding a load (the other is the
# loop increment). No PTR_ADD +0 should be inserted.
---
name:            phi_load_single_ptr_add_feeding_load
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi_load_single_ptr_add_feeding_load
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI %5(p0), %bb.1, [[PTR_ADD]](p0), %bb.0
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI %7(s32), %bb.1, [[COPY1]](s32), %bb.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PHI]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PHI]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s20)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI1]], [[C4]]
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[ADD]](s32), [[C5]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[LOAD1]](<16 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x2
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %100:_(s20) = G_CONSTANT i20 256
    %2:_(p0) = G_PTR_ADD %0, %100(s20)
    G_BR %bb.1

  bb.1:
    successors: %bb.2, %bb.1
    %3:_(p0) = G_PHI %10(p0), %bb.1, %2(p0), %bb.0
    %13:_(s32) = G_PHI %15(s32), %bb.1, %1(s32), %bb.0
    %7:_(<16 x s32>) = G_LOAD %3(p0) :: (load (<16 x s32>), align 64)
    %8:_(s20) = G_CONSTANT i20 128
    %9:_(p0) = G_PTR_ADD %3, %8(s20)
    %11:_(<16 x s32>) = G_LOAD %9(p0) :: (load (<16 x s32>), align 64)
    %12:_(s20) = G_CONSTANT i20 256
    %10:_(p0) = G_PTR_ADD %3, %12(s20)
    %14:_(s32) = G_CONSTANT i32 -1
    %15:_(s32) = G_ADD %13, %14
    %16:_(s32) = G_CONSTANT i32 0
    %17:_(s1) = G_ICMP intpred(eq), %15(s32), %16
    G_BRCOND %17(s1), %bb.2
    G_BR %bb.1

  bb.2:
    $x0 = COPY %7
    $x2 = COPY %11
    PseudoRET implicit $lr, implicit $x0, implicit $x2
...

# Negative test: no PTR_ADD +0 when address is not PHI-defined.
---
name:            non_phi_load_no_insert
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: non_phi_load_no_insert
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD]](p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD]], [[C2]](s20)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: $x0 = COPY [[LOAD]](<16 x s32>)
    ; CHECK-NEXT: $x2 = COPY [[LOAD1]](<16 x s32>)
    ; CHECK-NEXT: $x4 = COPY [[LOAD2]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0, implicit $x2, implicit $x4
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 -64
    %2:_(p0) = G_PTR_ADD %0, %1(s20)
    %3:_(<16 x s32>) = G_LOAD %2(p0) :: (load (<16 x s32>), align 64)
    %4:_(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>), align 64)
    %5:_(s20) = G_CONSTANT i20 64
    %6:_(p0) = G_PTR_ADD %0, %5(s20)
    %7:_(<16 x s32>) = G_LOAD %6(p0) :: (load (<16 x s32>), align 64)
    $x0 = COPY %3
    $x2 = COPY %4
    $x4 = COPY %7
    PseudoRET implicit $lr, implicit $x0, implicit $x2, implicit $x4
...

# Positive test: store at offset 0 from PHI also gets PTR_ADDs feeding stores.
---
name:            phi_store_bare_offset_zero
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi_store_bare_offset_zero
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(<8 x s64>) = COPY $x0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI %6(p0), %bb.1, [[PTR_ADD]](p0), %bb.0
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI %8(s32), %bb.1, [[COPY1]](s32), %bb.0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 -64
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PHI]], [[C1]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY2]](<8 x s64>), [[PTR_ADD1]](p0) :: (store (<8 x s64>))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY2]](<8 x s64>), [[PTR_ADD2]](p0) :: (store (<8 x s64>))
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD2]], [[C5]](s20)
  ; CHECK-NEXT:   G_STORE [[COPY2]](<8 x s64>), [[PTR_ADD3]](p0) :: (store (<8 x s64>))
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s20) = G_CONSTANT i20 192
  ; CHECK-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD3]], [[C7]](s20)
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI1]], [[C8]]
  ; CHECK-NEXT:   [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[ADD]](s32), [[C9]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0, $x0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %20:_(<8 x s64>) = COPY $x0
    %100:_(s20) = G_CONSTANT i20 128
    %2:_(p0) = G_PTR_ADD %0, %100(s20)
    G_BR %bb.1

  bb.1:
    successors: %bb.2, %bb.1
    %3:_(p0) = G_PHI %10(p0), %bb.1, %2(p0), %bb.0
    %13:_(s32) = G_PHI %15(s32), %bb.1, %1(s32), %bb.0
    %4:_(s20) = G_CONSTANT i20 -64
    %5:_(p0) = G_PTR_ADD %3, %4(s20)
    G_STORE %20(<8 x s64>), %5(p0) :: (store (<8 x s64>), align 64)
    G_STORE %20(<8 x s64>), %3(p0) :: (store (<8 x s64>), align 64)
    %8:_(s20) = G_CONSTANT i20 64
    %9:_(p0) = G_PTR_ADD %3, %8(s20)
    G_STORE %20(<8 x s64>), %9(p0) :: (store (<8 x s64>), align 64)
    %12:_(s20) = G_CONSTANT i20 256
    %10:_(p0) = G_PTR_ADD %3, %12(s20)
    %14:_(s32) = G_CONSTANT i32 -1
    %15:_(s32) = G_ADD %13, %14
    %16:_(s32) = G_CONSTANT i32 0
    %17:_(s1) = G_ICMP intpred(eq), %15(s32), %16
    G_BRCOND %17(s1), %bb.2
    G_BR %bb.1

  bb.2:
    PseudoRET implicit $lr
...

# Negative test: bare load from PHI appears BEFORE all G_PTR_ADDs that feed
# loads. The bare load is the first user of the PHI pointer and should NOT
# get G_PTR_ADD +0 inserted, because it can be combined with a post-increment
# update (e.g., add.2d/add.3d) into a single post-increment load instruction.
---
name:            phi_bare_load_before_ptr_adds_no_insert
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi_bare_load_before_ptr_adds_no_insert
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(p0) = G_PHI %5(p0), %bb.1, [[PTR_ADD]](p0), %bb.0
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI %7(s32), %bb.1, [[COPY1]](s32), %bb.0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PHI]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[PHI]], [[C1]](s20)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<16 x s32>))
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 256
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTR_ADD1]], [[C3]](s20)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI1]], [[C4]]
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[ADD]](s32), [[C5]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   $x0 = COPY [[LOAD]](<16 x s32>)
  ; CHECK-NEXT:   $x2 = COPY [[LOAD1]](<16 x s32>)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $x0, implicit $x2
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %100:_(s20) = G_CONSTANT i20 256
    %2:_(p0) = G_PTR_ADD %0, %100(s20)
    G_BR %bb.1

  bb.1:
    successors: %bb.2, %bb.1
    %3:_(p0) = G_PHI %10(p0), %bb.1, %2(p0), %bb.0
    %13:_(s32) = G_PHI %15(s32), %bb.1, %1(s32), %bb.0
    %7:_(<16 x s32>) = G_LOAD %3(p0) :: (load (<16 x s32>), align 64)
    %8:_(s20) = G_CONSTANT i20 128
    %9:_(p0) = G_PTR_ADD %3, %8(s20)
    %11:_(<16 x s32>) = G_LOAD %9(p0) :: (load (<16 x s32>), align 64)
    %12:_(s20) = G_CONSTANT i20 256
    %10:_(p0) = G_PTR_ADD %3, %12(s20)
    %14:_(s32) = G_CONSTANT i32 -1
    %15:_(s32) = G_ADD %13, %14
    %16:_(s32) = G_CONSTANT i32 0
    %17:_(s1) = G_ICMP intpred(eq), %15(s32), %16
    G_BRCOND %17(s1), %bb.2
    G_BR %bb.1

  bb.2:
    $x0 = COPY %7
    $x2 = COPY %11
    PseudoRET implicit $lr, implicit $x0, implicit $x2
...
