; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -mtriple=aie2p -passes=loop-reduce -S %s | FileCheck %s

; This test demonstrates a regression pattern where LSR creates pointer PHIs
; in the outer loop header for GEPs that are only used in the inner loop.
;
; Problem: The inner loop GEPs don't dominate the outer loop latch, but LSR
; creates pointer recurrences for them anyway. This causes:
;   1. Multiple pointer PHIs in outer loop header
;   2. Expensive padda/paddb/padds updates in outer loop latch
;   3. Unconditional pointer updates even when inner loop wasn't entered
;
; Expected: LSR should use scalar index recurrence + indexed addressing,
; keeping pointer computation where it's actually used.
;
; Reference (good): vldb x8, [p3, dj1]  with  add r27, r27, r24  in latch
; Regressed (bad):  vldb x8, [p6], #64  with  padda [p3], m1; padda [p7], m1  in latch

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p"

; Test: Nested loop where inner loop GEPs should NOT create outer loop pointer PHIs
;
; The inner loop should use scalar i20 recurrence + indexed addressing,
; not pointer recurrence which would require expensive updates in outer latch.
;
; CHECK-LABEL: define void @nested_loop_non_dominating
; CHECK: inner_header:
; CHECK: [[IV:%.*]] = phi i20
; CHECK: [[PTR:%.*]] = getelementptr i8, ptr {{%.*}}, i20 [[IV]]
; CHECK: load <32 x i16>, ptr [[PTR]]
; CHECK: add i20 [[IV]], 64
define void @nested_loop_non_dominating(ptr %base, i32 %outer_n, i32 %inner_n, i32 %stride) {
entry:
  %stride20 = trunc i32 %stride to i20
  br label %outer_header

outer_header:
  %outer_i = phi i32 [ 0, %entry ], [ %outer_next, %outer_latch ]
  %outer_cmp = icmp slt i32 %outer_i, %outer_n
  br i1 %outer_cmp, label %inner_preheader, label %exit

inner_preheader:
  ; Compute base offset for this outer iteration
  %outer_offset_32 = mul i32 %outer_i, %stride
  %outer_offset = trunc i32 %outer_offset_32 to i20
  %outer_ptr = getelementptr i8, ptr %base, i20 %outer_offset
  br label %inner_header

inner_header:
  %inner_i = phi i32 [ 0, %inner_preheader ], [ %inner_next, %inner_header ]
  ; This GEP is inside inner loop - should NOT create pointer PHI in outer_header
  %inner_offset_32 = mul i32 %inner_i, 64
  %inner_offset = trunc i32 %inner_offset_32 to i20
  %inner_ptr = getelementptr i8, ptr %outer_ptr, i20 %inner_offset
  
  %val = load <32 x i16>, ptr %inner_ptr, align 64
  call void @consume(<32 x i16> %val)
  
  %inner_next = add i32 %inner_i, 1
  %inner_cmp = icmp slt i32 %inner_next, %inner_n
  br i1 %inner_cmp, label %inner_header, label %outer_latch

outer_latch:
  ; Only scalar add should happen here, NOT pointer updates
  %outer_next = add i32 %outer_i, 1
  br label %outer_header

exit:
  ret void
}

; Test: Multiple arrays in nested loop - even worse regression
; Each array creates its own pointer PHI, multiplying outer latch cost
;
; CHECK-LABEL: define void @nested_loop_multiple_arrays
; CHECK: outer_header:
; Outer loop should have scalar i20 PHI, not pointer PHIs
; CHECK: phi i20
; CHECK: inner_header:
; Inner loop should use scalar i20 recurrence
; CHECK: [[INNER_IV:%.*]] = phi i20
; CHECK: getelementptr i8, ptr {{%.*}}, i20 [[INNER_IV]]
; CHECK: outer_latch:
; Outer latch should have scalar add, not multiple pointer scevgeps
; CHECK: add i20
define void @nested_loop_multiple_arrays(ptr %a, ptr %b, ptr %c, i32 %outer_n, i32 %inner_n, i32 %stride) {
entry:
  %stride20 = trunc i32 %stride to i20
  br label %outer_header

outer_header:
  %outer_i = phi i32 [ 0, %entry ], [ %outer_next, %outer_latch ]
  %outer_cmp = icmp slt i32 %outer_i, %outer_n
  br i1 %outer_cmp, label %inner_preheader, label %exit

inner_preheader:
  %outer_offset_32 = mul i32 %outer_i, %stride
  %outer_offset = trunc i32 %outer_offset_32 to i20
  %ptr_a = getelementptr i8, ptr %a, i20 %outer_offset
  %ptr_b = getelementptr i8, ptr %b, i20 %outer_offset
  %ptr_c = getelementptr i8, ptr %c, i20 %outer_offset
  br label %inner_header

inner_header:
  %inner_i = phi i32 [ 0, %inner_preheader ], [ %inner_next, %inner_header ]
  %inner_offset_32 = mul i32 %inner_i, 64
  %inner_offset = trunc i32 %inner_offset_32 to i20
  
  ; Three GEPs - should NOT create 3 pointer PHIs in outer_header
  %inner_a = getelementptr i8, ptr %ptr_a, i20 %inner_offset
  %inner_b = getelementptr i8, ptr %ptr_b, i20 %inner_offset
  %inner_c = getelementptr i8, ptr %ptr_c, i20 %inner_offset
  
  %val_a = load <32 x i16>, ptr %inner_a, align 64
  %val_b = load <32 x i16>, ptr %inner_b, align 64
  %sum = add <32 x i16> %val_a, %val_b
  store <32 x i16> %sum, ptr %inner_c, align 64
  
  %inner_next = add i32 %inner_i, 1
  %inner_cmp = icmp slt i32 %inner_next, %inner_n
  br i1 %inner_cmp, label %inner_header, label %outer_latch

outer_latch:
  %outer_next = add i32 %outer_i, 1
  br label %outer_header

exit:
  ret void
}

declare void @consume(<32 x i16>)
