; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -mtriple=aie2p -passes=loop-reduce -S %s | FileCheck %s

; This test is extracted from Topk2D_bf16_1.ii to verify LSR behavior for
; nested loops with trunc->GEP patterns in the outer loop.
;
; The pattern is:
; - Outer loop (for.body8) computes: mul -> trunc to i20 -> GEP
; - Inner loop (for.body17) uses the GEP result
;
; LSR creates an i20 recurrence for the outer loop since i20 is a valid IV
; type for AIE (via isValidIVUserType TTI hook). This is acceptable as long
; as the shouldIVUsersLookThroughInst hook doesn't also trigger for the outer
; loop (which has subloops), which would cause additional expensive operations.

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p"



define void @outer_loop_trunc_gep(ptr noalias %ifm_data, ptr noalias %ofm_data, i32 %H, i32 %K, i32 %stride) {
; CHECK-LABEL: define void @outer_loop_trunc_gep(
; CHECK-SAME: ptr noalias [[IFM_DATA:%.*]], ptr noalias [[OFM_DATA:%.*]], i32 [[H:%.*]], i32 [[K:%.*]], i32 [[STRIDE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[H]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY8_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[FOR_BODY8_PREHEADER]]:
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i32 [[STRIDE]] to i20
; CHECK-NEXT:    br label %[[FOR_BODY8:.*]]
; CHECK:       [[FOR_BODY8]]:
; CHECK-NEXT:    [[LSR_IV1:%.*]] = phi i20 [ [[LSR_IV_NEXT:%.*]], %[[FOR_COND_CLEANUP17:.*]] ], [ 0, %[[FOR_BODY8_PREHEADER]] ]
; CHECK-NEXT:    [[I_H:%.*]] = phi i32 [ 0, %[[FOR_BODY8_PREHEADER]] ], [ [[INC_H:%.*]], %[[FOR_COND_CLEANUP17]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = getelementptr inbounds bfloat, ptr [[IFM_DATA]], i20 [[LSR_IV1]]
; CHECK-NEXT:    br label %[[FOR_BODY17:.*]]
; CHECK:       [[FOR_BODY17]]:
; CHECK-NEXT:    [[I12:%.*]] = phi i32 [ 0, %[[FOR_BODY8]] ], [ [[INC12:%.*]], %[[FOR_BODY17]] ]
; CHECK-NEXT:    [[VAL:%.*]] = load <32 x i16>, ptr [[LSR_IV]], align 64
; CHECK-NEXT:    call void @use(<32 x i16> [[VAL]])
; CHECK-NEXT:    [[INC12]] = add i32 [[I12]], 1
; CHECK-NEXT:    [[CMP17:%.*]] = icmp slt i32 [[INC12]], [[K]]
; CHECK-NEXT:    br i1 [[CMP17]], label %[[FOR_BODY17]], label %[[FOR_COND_CLEANUP17]]
; CHECK:       [[FOR_COND_CLEANUP17]]:
; CHECK-NEXT:    [[INC_H]] = add i32 [[I_H]], 1
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i20 [[LSR_IV1]], [[TMP0]]
; CHECK-NEXT:    [[CMP8:%.*]] = icmp slt i32 [[INC_H]], [[H]]
; CHECK-NEXT:    br i1 [[CMP8]], label %[[FOR_BODY8]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %cmp = icmp sgt i32 %H, 0
  br i1 %cmp, label %for.body8.preheader, label %exit

for.body8.preheader:
  br label %for.body8

for.body8:
  %i_h = phi i32 [ 0, %for.body8.preheader ], [ %inc_h, %for.cond.cleanup17 ]
  ; This is the key pattern: mul -> trunc -> GEP in outer loop
  %mul9 = mul i32 %stride, %i_h
  %idx.ext10 = trunc i32 %mul9 to i20
  %add.ptr11 = getelementptr inbounds bfloat, ptr %ifm_data, i20 %idx.ext10
  br label %for.body17

for.body17:
  %i12 = phi i32 [ 0, %for.body8 ], [ %inc12, %for.body17 ]
  ; Inner loop uses the GEP from outer loop
  %val = load <32 x i16>, ptr %add.ptr11, align 64
  call void @use(<32 x i16> %val)
  %inc12 = add i32 %i12, 1
  %cmp17 = icmp slt i32 %inc12, %K
  br i1 %cmp17, label %for.body17, label %for.cond.cleanup17

for.cond.cleanup17:
  %inc_h = add i32 %i_h, 1
  %cmp8 = icmp slt i32 %inc_h, %H
  br i1 %cmp8, label %for.body8, label %exit

exit:
  ret void
}

declare void @use(<32 x i16>)
