; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -mtriple=aie2p -passes=loop-reduce -S %s | FileCheck %s

; This test verifies that LSR preserves pointer recurrences on AIE targets.
; AIE processors support post-increment addressing modes (VLD_pstm, VST_pstm)
; that fold pointer updates into memory operations for free. LSR should NOT
; rewrite pointer PHIs to scalar offset + base formulas, as this would
; prevent post-increment combining and introduce extra PADD instructions.
;
; Specifically, this test checks that:
; 1. Pointer PHIs are preserved (not rewritten to %scevgep or similar)
; 2. GEP chains retain their original structure with inbounds
; 3. addrspacecast operations don't trigger unwanted IV chain processing

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p"

; Test: Multiple pointer recurrences with variable stride through addrspacecast
; The pointer PHIs should be preserved as-is, not rewritten by LSR.
;
define void @multi_pointer_addrspacecast(ptr %ifm, ptr %ofm, i20 %stride, i32 %n) {
; CHECK-LABEL: define void @multi_pointer_addrspacecast(
; CHECK-SAME: ptr [[IFM:%.*]], ptr [[OFM:%.*]], i20 [[STRIDE:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[P_IFM:%.*]] = phi ptr [ [[IFM]], %[[ENTRY]] ], [ [[NEXT_IFM:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P_OFM:%.*]] = phi ptr [ [[OFM]], %[[ENTRY]] ], [ [[NEXT_OFM:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IFM_AS:%.*]] = addrspacecast ptr [[P_IFM]] to ptr addrspace(5)
; CHECK-NEXT:    [[OFM_AS:%.*]] = addrspacecast ptr [[P_OFM]] to ptr addrspace(7)
; CHECK-NEXT:    [[VAL:%.*]] = load <16 x i32>, ptr addrspace(5) [[IFM_AS]], align 64
; CHECK-NEXT:    store <16 x i32> [[VAL]], ptr addrspace(7) [[OFM_AS]], align 64
; CHECK-NEXT:    [[NEXT_IFM]] = getelementptr inbounds i8, ptr [[P_IFM]], i20 [[STRIDE]]
; CHECK-NEXT:    [[NEXT_OFM]] = getelementptr inbounds i8, ptr [[P_OFM]], i20 [[STRIDE]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %p_ifm = phi ptr [ %ifm, %entry ], [ %next_ifm, %loop ]
  %p_ofm = phi ptr [ %ofm, %entry ], [ %next_ofm, %loop ]
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]

  %ifm_as = addrspacecast ptr %p_ifm to ptr addrspace(5)
  %ofm_as = addrspacecast ptr %p_ofm to ptr addrspace(7)

  %val = load <16 x i32>, ptr addrspace(5) %ifm_as, align 64
  store <16 x i32> %val, ptr addrspace(7) %ofm_as, align 64

  %next_ifm = getelementptr inbounds i8, ptr %p_ifm, i20 %stride
  %next_ofm = getelementptr inbounds i8, ptr %p_ofm, i20 %stride

  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Test: GEP chain within a loop (multiple loads at offsets)
; This pattern can form IV chains in LSR. LSR should NOT rewrite these.
;
define void @gep_chain_pattern(ptr %base, i20 %stride, i32 %n) {
; CHECK-LABEL: define void @gep_chain_pattern(
; CHECK-SAME: ptr [[BASE:%.*]], i20 [[STRIDE:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[P:%.*]] = phi ptr [ [[BASE]], %[[ENTRY]] ], [ [[P3:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[AS0:%.*]] = addrspacecast ptr [[P]] to ptr addrspace(5)
; CHECK-NEXT:    [[V0:%.*]] = load <16 x i32>, ptr addrspace(5) [[AS0]], align 64
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds i8, ptr [[P]], i20 [[STRIDE]]
; CHECK-NEXT:    [[AS1:%.*]] = addrspacecast ptr [[P1]] to ptr addrspace(5)
; CHECK-NEXT:    [[V1:%.*]] = load <16 x i32>, ptr addrspace(5) [[AS1]], align 64
; CHECK-NEXT:    [[P2:%.*]] = getelementptr inbounds i8, ptr [[P1]], i20 [[STRIDE]]
; CHECK-NEXT:    [[AS2:%.*]] = addrspacecast ptr [[P2]] to ptr addrspace(5)
; CHECK-NEXT:    [[V2:%.*]] = load <16 x i32>, ptr addrspace(5) [[AS2]], align 64
; CHECK-NEXT:    [[P3]] = getelementptr inbounds i8, ptr [[P2]], i20 [[STRIDE]]
; CHECK-NEXT:    call void @consume(<16 x i32> [[V0]])
; CHECK-NEXT:    call void @consume(<16 x i32> [[V1]])
; CHECK-NEXT:    call void @consume(<16 x i32> [[V2]])
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %p = phi ptr [ %base, %entry ], [ %p3, %loop ]
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]

  %as0 = addrspacecast ptr %p to ptr addrspace(5)
  %v0 = load <16 x i32>, ptr addrspace(5) %as0, align 64

  %p1 = getelementptr inbounds i8, ptr %p, i20 %stride
  %as1 = addrspacecast ptr %p1 to ptr addrspace(5)
  %v1 = load <16 x i32>, ptr addrspace(5) %as1, align 64

  %p2 = getelementptr inbounds i8, ptr %p1, i20 %stride
  %as2 = addrspacecast ptr %p2 to ptr addrspace(5)
  %v2 = load <16 x i32>, ptr addrspace(5) %as2, align 64

  %p3 = getelementptr inbounds i8, ptr %p2, i20 %stride

  call void @consume(<16 x i32> %v0)
  call void @consume(<16 x i32> %v1)
  call void @consume(<16 x i32> %v2)

  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

declare void @consume(<16 x i32>)

; Test: i20 scalar recurrences should still be handled by LSR
; This ensures the IVUsers change doesn't break i20 integer optimization
;
define i20 @i20_scalar_recurrence(i20 %n, i20 %step) {
; CHECK-LABEL: define i20 @i20_scalar_recurrence(
; CHECK-SAME: i20 [[N:%.*]], i20 [[STEP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i20 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi i20 [ 0, %[[ENTRY]] ], [ [[SUM_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM_NEXT]] = add i20 [[SUM]], [[I]]
; CHECK-NEXT:    [[I_NEXT]] = add i20 [[I]], [[STEP]]
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i20 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SUM_NEXT_LCSSA:%.*]] = phi i20 [ [[SUM_NEXT]], %[[LOOP]] ]
; CHECK-NEXT:    ret i20 [[SUM_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %i = phi i20 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i20 [ 0, %entry ], [ %sum.next, %loop ]

  %sum.next = add i20 %sum, %i
  %i.next = add i20 %i, %step

  %cond = icmp slt i20 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret i20 %sum.next
}
