; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -mtriple=aie2p -passes='print<iv-users>' -disable-output %s 2>&1 | FileCheck %s --check-prefix=IVUSERS
; RUN: opt -mtriple=aie2p -passes=loop-reduce -S %s | FileCheck %s --check-prefix=LSR

; This test verifies that LSR correctly handles i20 scalar recurrences on AIE.
; The pattern is derived from a post_process kernel where:
; - Loop counter is i32
; - Array indices are computed as (4 * i + offset) and truncated to i20
; - Multiple loads/stores at offsets 0, 1, 2, 3 from the scaled index
;
; LSR should:
; 1. Recognize i20 truncated indices as IV users (for potential optimization)
; 2. NOT rewrite pointer recurrences (preserve GEP structure for post-increment)
; 3. Allow the loop to use native i20 addressing

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p"

; Check that i20 indices are collected as IV users
; IVUSERS: IV Users for loop %for.body with backedge-taken count
; IVUSERS: %idx{{[0-3]}} = {{{[0-3]}},+,4}<%for.body>

; Check that LSR creates an i20 recurrence for native addressing
; The key optimization: instead of computing trunc(4*i + offset) each time,
; LSR creates an i20 PHI that increments by 4 directly.

define void @post_process_pattern(ptr nocapture %src, i32 noundef %len) {
; LSR-LABEL: define void @post_process_pattern(
; LSR-SAME: ptr nocapture [[SRC:%.*]], i32 noundef [[LEN:%.*]]) {
; LSR-NEXT:  [[ENTRY:.*]]:
; LSR-NEXT:    [[DIV:%.*]] = lshr i32 [[LEN]], 7
; LSR-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[LEN]], 511
; LSR-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; LSR-NEXT:    [[TMP0:%.*]] = shl nuw nsw i32 [[DIV]], 2
; LSR-NEXT:    br label %[[FOR_BODY:.*]]
; LSR:       [[FOR_COND_CLEANUP:.*]]:
; LSR-NEXT:    ret void
; LSR:       [[FOR_BODY]]:
; LSR-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ 0, %[[ENTRY]] ]
; LSR-NEXT:    [[IDX0:%.*]] = trunc i32 [[LSR_IV]] to i20
; LSR-NEXT:    [[PTR0:%.*]] = getelementptr inbounds <32 x float>, ptr [[SRC]], i20 [[IDX0]]
; LSR-NEXT:    [[V0:%.*]] = load <32 x float>, ptr [[PTR0]], align 64
; LSR-NEXT:    [[R0:%.*]] = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> [[V0]])
; LSR-NEXT:    [[DST0:%.*]] = getelementptr inbounds <32 x bfloat>, ptr [[SRC]], i20 [[IDX0]]
; LSR-NEXT:    store <32 x bfloat> [[R0]], ptr [[DST0]], align 64
; LSR-NEXT:    [[TMP1:%.*]] = add i32 [[LSR_IV]], 1
; LSR-NEXT:    [[IDX1:%.*]] = trunc i32 [[TMP1]] to i20
; LSR-NEXT:    [[PTR1:%.*]] = getelementptr inbounds <32 x float>, ptr [[SRC]], i20 [[IDX1]]
; LSR-NEXT:    [[V1:%.*]] = load <32 x float>, ptr [[PTR1]], align 64
; LSR-NEXT:    [[R1:%.*]] = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> [[V1]])
; LSR-NEXT:    [[DST1:%.*]] = getelementptr inbounds <32 x bfloat>, ptr [[SRC]], i20 [[IDX1]]
; LSR-NEXT:    store <32 x bfloat> [[R1]], ptr [[DST1]], align 64
; LSR-NEXT:    [[TMP2:%.*]] = add i32 [[LSR_IV]], 2
; LSR-NEXT:    [[IDX2:%.*]] = trunc i32 [[TMP2]] to i20
; LSR-NEXT:    [[PTR2:%.*]] = getelementptr inbounds <32 x float>, ptr [[SRC]], i20 [[IDX2]]
; LSR-NEXT:    [[V2:%.*]] = load <32 x float>, ptr [[PTR2]], align 64
; LSR-NEXT:    [[R2:%.*]] = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> [[V2]])
; LSR-NEXT:    [[DST2:%.*]] = getelementptr inbounds <32 x bfloat>, ptr [[SRC]], i20 [[IDX2]]
; LSR-NEXT:    store <32 x bfloat> [[R2]], ptr [[DST2]], align 64
; LSR-NEXT:    [[TMP3:%.*]] = add i32 [[LSR_IV]], 3
; LSR-NEXT:    [[IDX3:%.*]] = trunc i32 [[TMP3]] to i20
; LSR-NEXT:    [[PTR3:%.*]] = getelementptr inbounds <32 x float>, ptr [[SRC]], i20 [[IDX3]]
; LSR-NEXT:    [[V3:%.*]] = load <32 x float>, ptr [[PTR3]], align 64
; LSR-NEXT:    [[R3:%.*]] = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> [[V3]])
; LSR-NEXT:    [[DST3:%.*]] = getelementptr inbounds <32 x bfloat>, ptr [[SRC]], i20 [[IDX3]]
; LSR-NEXT:    store <32 x bfloat> [[R3]], ptr [[DST3]], align 64
; LSR-NEXT:    [[LSR_IV_NEXT]] = add nuw nsw i32 [[LSR_IV]], 4
; LSR-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[TMP0]], [[LSR_IV_NEXT]]
; LSR-NEXT:    br i1 [[EXITCOND]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
;
entry:
  %div = lshr i32 %len, 7
  %cmp = icmp sgt i32 %len, 511
  tail call void @llvm.assume(i1 %cmp)
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %i = phi i32 [ 0, %entry ], [ %inc, %for.body ]

  ; Compute base index: 4 * i
  %mul = shl nsw i32 %i, 2
  %idx0 = trunc i32 %mul to i20

  ; Load at offset 0
  %ptr0 = getelementptr inbounds <32 x float>, ptr %src, i20 %idx0
  %v0 = load <32 x float>, ptr %ptr0, align 64
  %r0 = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %v0)
  %dst0 = getelementptr inbounds <32 x bfloat>, ptr %src, i20 %idx0
  store <32 x bfloat> %r0, ptr %dst0, align 64

  ; Load at offset 1
  %add1 = or disjoint i32 %mul, 1
  %idx1 = trunc i32 %add1 to i20
  %ptr1 = getelementptr inbounds <32 x float>, ptr %src, i20 %idx1
  %v1 = load <32 x float>, ptr %ptr1, align 64
  %r1 = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %v1)
  %dst1 = getelementptr inbounds <32 x bfloat>, ptr %src, i20 %idx1
  store <32 x bfloat> %r1, ptr %dst1, align 64

  ; Load at offset 2
  %add2 = or disjoint i32 %mul, 2
  %idx2 = trunc i32 %add2 to i20
  %ptr2 = getelementptr inbounds <32 x float>, ptr %src, i20 %idx2
  %v2 = load <32 x float>, ptr %ptr2, align 64
  %r2 = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %v2)
  %dst2 = getelementptr inbounds <32 x bfloat>, ptr %src, i20 %idx2
  store <32 x bfloat> %r2, ptr %dst2, align 64

  ; Load at offset 3
  %add3 = or disjoint i32 %mul, 3
  %idx3 = trunc i32 %add3 to i20
  %ptr3 = getelementptr inbounds <32 x float>, ptr %src, i20 %idx3
  %v3 = load <32 x float>, ptr %ptr3, align 64
  %r3 = tail call <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %v3)
  %dst3 = getelementptr inbounds <32 x bfloat>, ptr %src, i20 %idx3
  store <32 x bfloat> %r3, ptr %dst3, align 64

  %inc = add nuw nsw i32 %i, 1
  %exitcond = icmp eq i32 %inc, %div
  br i1 %exitcond, label %for.cond.cleanup, label %for.body, !llvm.loop !0
}

declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>)
declare void @llvm.assume(i1 noundef)

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.itercount.range", i64 4}
;.
; LSR: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; LSR: [[META1]] = !{!"llvm.loop.itercount.range", i64 4}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; IVUSERS: {{.*}}
