; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt -mtriple=aie2p -passes=loop-reduce -S %s | FileCheck %s

; This test is extracted from Topk2D_bf16_1.ii to verify LSR behavior for
; nested loops with trunc->GEP patterns in the outer loop.
;
; The pattern is:
; - Outer loop (for.body8) computes: mul -> trunc to i20 -> GEP
; - Inner loop (for.body17) uses the GEP result
;
; Baseline behavior: LSR creates an i32 recurrence and truncates per iteration.

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p"

; CHECK-LABEL: define void @outer_loop_trunc_gep(
; CHECK: for.body8.preheader:
; CHECK: br label %for.body8
;
; CHECK: for.body8:
; Baseline: LSR creates i32 recurrence, truncates per iteration
; CHECK: [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], %for.cond.cleanup17 ], [ 0, %for.body8.preheader ]
; CHECK: [[I_H:%.*]] = phi i32
; CHECK: [[TRUNC:%.*]] = trunc i32 [[LSR_IV]] to i20
; CHECK: [[GEP:%.*]] = getelementptr inbounds bfloat, ptr %ifm_data, i20 [[TRUNC]]
; CHECK: br label %for.body17
;
; CHECK: for.body17:
; CHECK: br i1 {{.*}}, label %for.body17, label %for.cond.cleanup17
;
; CHECK: for.cond.cleanup17:
; CHECK: [[INC_H:%.*]] = add i32 [[I_H]], 1
; CHECK: [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], %stride
; CHECK: br i1 {{.*}}, label %for.body8, label %exit

define void @outer_loop_trunc_gep(ptr noalias %ifm_data, ptr noalias %ofm_data, i32 %H, i32 %K, i32 %stride) {
entry:
  %cmp = icmp sgt i32 %H, 0
  br i1 %cmp, label %for.body8.preheader, label %exit

for.body8.preheader:
  br label %for.body8

for.body8:
  %i_h = phi i32 [ 0, %for.body8.preheader ], [ %inc_h, %for.cond.cleanup17 ]
  ; This is the key pattern: mul -> trunc -> GEP in outer loop
  %mul9 = mul i32 %stride, %i_h
  %idx.ext10 = trunc i32 %mul9 to i20
  %add.ptr11 = getelementptr inbounds bfloat, ptr %ifm_data, i20 %idx.ext10
  br label %for.body17

for.body17:
  %i12 = phi i32 [ 0, %for.body8 ], [ %inc12, %for.body17 ]
  ; Inner loop uses the GEP from outer loop
  %val = load <32 x i16>, ptr %add.ptr11, align 64
  call void @use(<32 x i16> %val)
  %inc12 = add i32 %i12, 1
  %cmp17 = icmp slt i32 %inc12, %K
  br i1 %cmp17, label %for.body17, label %for.cond.cleanup17

for.cond.cleanup17:
  %inc_h = add i32 %i_h, 1
  %cmp8 = icmp slt i32 %inc_h, %H
  br i1 %cmp8, label %for.body8, label %exit

exit:
  ret void
}

declare void @use(<32 x i16>)
