; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p --enable-pipeliner=0 %s -o - | FileCheck %s

; llvm.vector.insert lowers to G_INSERT_SUBVECTOR, which previously had no
; AIE2P legalizer rule at all and hit a fatal "unable to legalize
; instruction" on this input.
define void @insert_subvector_v8i8_into_v16i8(<8 x i8> %sub, ptr %p) {
; CHECK-LABEL: insert_subvector_v8i8_into_v16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nopx ; vextract.8 r2, x0, #8, vaddsign1
; CHECK-NEXT:    mova r4, #-8; vextract.8 r3, x0, #9, vaddsign1
; CHECK-NEXT:    mova r7, #24; lshl r6, r0, r4; vextract.8 r5, x0, #10, vaddsign1
; CHECK-NEXT:    mova r19, #16; lshl r7, r1, r7; vextract.8 r16, x0, #11, vaddsign1
; CHECK-NEXT:    mova r22, #8; lshl r19, r1, r19; vextract.8 r17, x0, #12, vaddsign1
; CHECK-NEXT:    lshl r22, r1, r22; vextract.8 r18, x0, #13, vaddsign1
; CHECK-NEXT:    mova r7, #-16; or r6, r6, r7; vextract.8 r21, x0, #14, vaddsign1
; CHECK-NEXT:    lshl r20, r0, r7; vpush.hi.8 x0, x0, r0
; CHECK-NEXT:    mova r20, #-24; or r19, r20, r19; vpush.hi.8 x0, x0, r6
; CHECK-NEXT:    lshl r0, r0, r20; vextract.8 r6, x0, #15, vaddsign1
; CHECK-NEXT:    or r0, r0, r22; vpush.hi.8 x0, x0, r19
; CHECK-NEXT:    vpush.hi.8 x0, x0, r0
; CHECK-NEXT:    lshl r0, r1, r4; vpush.hi.8 x0, x0, r1
; CHECK-NEXT:    lshl r4, r1, r7; vpush.hi.8 x0, x0, r0
; CHECK-NEXT:    lshl r0, r1, r20; vpush.hi.8 x0, x0, r4
; CHECK-NEXT:    vpush.hi.8 x0, x0, r0
; CHECK-NEXT:    vpush.hi.8 x0, x0, r2
; CHECK-NEXT:    vpush.hi.8 x0, x0, r3
; CHECK-NEXT:    vpush.hi.8 x0, x0, r5
; CHECK-NEXT:    vpush.hi.8 x0, x0, r16
; CHECK-NEXT:    vpush.hi.8 x0, x0, r17
; CHECK-NEXT:    vpush.hi.8 x0, x0, r18
; CHECK-NEXT:    ret lr; vpush.hi.8 x0, x0, r21
; CHECK-NEXT:    mova r0, #48; vpush.hi.8 x0, x0, r6 // Delay Slot 5
; CHECK-NEXT:    vshift x0, x0, x0, r0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vst.128 wl0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %r = call <16 x i8> @llvm.vector.insert.v16i8.v8i8(<16 x i8> poison, <8 x i8> %sub, i64 0)
  store <16 x i8> %r, ptr %p, align 16
  ret void
}

declare <16 x i8> @llvm.vector.insert.v16i8.v8i8(<16 x i8>, <8 x i8>, i64)
